services:
  jaeger:
    image: jaegertracing/jaeger:2.17.0
    volumes:
      - ./jaeger.yaml:/etc/jaeger/config.yaml:ro
    command:
      - "--config"
      - "/etc/jaeger/config.yaml"
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
    ports:
      - "127.0.0.1:16686:16686"  # Jaeger UI
      - "127.0.0.1:4317:4317"    # OTLP gRPC
      - "127.0.0.1:4318:4318"    # OTLP HTTP
    networks:
      - atomic-network
    restart: always

  deez-nutz:
    image: nats:2.12.8-alpine
    command: ["-c", "/etc/nats.conf", "-js"]
    volumes:
      - ./nats.conf:/etc/nats.conf:ro
      - deez-nutz-data:/data
    environment:
      - NATS_TOKEN=${NATS_TOKEN}
      - NATS_PORT=${NATS_PORT}
    ports:
      - "127.0.0.1:${NATS_PORT}:${NATS_PORT}"
    networks:
      - atomic-network
    restart: always

  redis:
    image: redis:8.0-alpine
    restart: always
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - atomic-network

  ws:
    build:
      context: ./go
      dockerfile: Dockerfile.dev
    command: air -c .air.ws.toml
    environment:
      # Log level
      - LOG_LEVEL=${LOG_LEVEL:-info}
      # WS
      - WS_PORT=${WS_PORT}
      # NATS
      - NATS_HOST=${NATS_HOST}
      - NATS_PORT=${NATS_PORT}
      - NATS_TOKEN=${NATS_TOKEN}
      - NATS_STREAM_TASKS=${NATS_STREAM_TASKS}
      - NATS_SUBJECT_BROADCAST=${NATS_SUBJECT_BROADCAST}
      # Public data (welcome message)
      - QUEUE_CAPACITY=${QUEUE_CAPACITY}
      - SERVER_WORKER_NUM=${SERVER_WORKER_NUM}
      - METRICS_UPDATE_INTERVAL_MS=${METRICS_UPDATE_INTERVAL_MS}
    ports:
      - "127.0.0.1:${WS_PORT}:${WS_PORT}"
    volumes:
      - ./go:/app
      - go-mod-cache:/go/pkg/mod
    networks:
      - atomic-network
    depends_on:
      - deez-nutz
      - jaeger

  balancer:
    build:
      context: ./go
      dockerfile: Dockerfile.dev
    command: air -c .air.balancer.toml
    environment:
      # Log level
      - LOG_LEVEL=${LOG_LEVEL:-info}
      # Balancer & API
      - API_TOKEN=${API_TOKEN}
      - API_PORT=${API_PORT}
      # Redis
      - REDIS_URL=${REDIS_URL}
    ports:
      - "127.0.0.1:${API_PORT}:${API_PORT}"
    volumes:
      - ./go:/app
      - go-mod-cache:/go/pkg/mod
    networks:
      - atomic-network
    depends_on:
      - ws
      - redis
      - jaeger

  api:
    build:
      context: ./go
      dockerfile: Dockerfile.dev
    command: air -c .air.api.toml
    environment:
      # Log level
      - LOG_LEVEL=${LOG_LEVEL:-info}
      # Balancer & API
      - API_PORT=8080 # Isolated runtime port for scaling instances within the network
      - API_TOKEN=${API_TOKEN}
      - API_URL=${API_URL}
      # Redis
      - REDIS_URL=${REDIS_URL}
    volumes:
      - ./go:/app
      - go-mod-cache:/go/pkg/mod
    networks:
      - atomic-network
    depends_on:
      - ws
      - redis
      - jaeger

volumes:
  deez-nutz-data:
  go-mod-cache:

networks:
  atomic-network:
    driver: bridge