services:
  app:
    image: ghcr.io/shmandalf/fast-atomic-flow:latest
    container_name: atomic-flow-app
    restart: always
    env_file:
      - .env
    depends_on:
      - deez-nutz
      - ws-proxy
    ports:
      - "${SERVER_PORT:-9501}:${SERVER_PORT:-9501}"
    logging:
      driver: "json-file"
      options:
        max-size: "10m" # < 10Mb
        max-file: "3"   # Keep 3 files max
    networks:
      - atomic-network

  deez-nutz:
    image: nats:2.12.8-alpine
    container_name: fast-deez-nutz
    command: ["-c", "/etc/nats.conf", "-js"]
    restart: always
    volumes:
      - ./nats.conf:/etc/nats.conf:ro
      - deez-nutz-data:/data
    ports:
      - "127.0.0.1:4222:4222"
    environment:
      - NATS_TOKEN=${NATS_TOKEN}
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    networks:
      - atomic-network

  ws-proxy:
    image: ghcr.io/shmandalf/fast-atomic-flow-ws:latest
    container_name: fast-ws
    restart: always
    command: /usr/local/bin/go-proxy
    environment:
      - APP_VERSION=${APP_VERSION:-dev}
    env_file:
      - .env
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - atomic-network
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    depends_on:
      - deez-nutz

  api:
    image: ghcr.io/shmandalf/fast-atomic-flow-api:latest
    container_name: fast-api
    restart: always
    command: /usr/local/bin/api
    environment:
      - APP_VERSION=${APP_VERSION:-dev}
    env_file:
      - .env
    ports:
      - "127.0.0.1:8081:8081"
    networks:
      - atomic-network
    depends_on:
      - ws-proxy

volumes:
  deez-nutz-data:

networks:
  atomic-network:
    driver: bridge
