services:
  app:
    image: ghcr.io/centaur-vova/fast-atomic-flow:latest
    restart: always
    env_file:
      - .env
    depends_on:
      - deez-nutz
      - ws
    ports:
      - "${SERVER_PORT:-9501}:${SERVER_PORT:-9501}"
    logging:
      driver: "json-file"
      options:
        max-size: "10m" # < 10Mb
        max-file: "3"   # Keep 3 files max
    networks:
      - atomic-network

  deez-nutz:
    image: nats:2.12.8-alpine
    command: ["-c", "/etc/nats.conf", "-js"]
    restart: always
    volumes:
      - ./nats.conf:/etc/nats.conf:ro
      - deez-nutz-data:/data
    ports:
      - "127.0.0.1:4222:4222"
    environment:
      - NATS_TOKEN=${NATS_TOKEN}
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    networks:
      - atomic-network

  ws:
    image: ghcr.io/centaur-vova/fast-atomic-flow-ws:latest
    restart: always
    command: /usr/local/bin/go-proxy
    environment:
      - NATS_TOKEN=${NATS_TOKEN}
    env_file:
      - .env
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - atomic-network
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    depends_on:
      - deez-nutz

  balancer:
    image: ghcr.io/centaur-vova/fast-atomic-flow-balancer:latest
    restart: always
    command: /usr/local/bin/balancer
    environment:
      - PORT=8090
    ports:
      - "127.0.0.1:8090:8090"
    networks:
      - atomic-network
    depends_on:
      - api-1
      - api-2
      - api-3

  api:
    image: ghcr.io/centaur-vova/fast-atomic-flow-api:latest
    restart: always
    command: /usr/local/bin/api
    environment:
      - API_PORT=8081
    env_file:
      - .env
    networks:
      - atomic-network
    depends_on:
      - ws

volumes:
  deez-nutz-data:

networks:
  atomic-network:
    driver: bridge
