services:
  nutz:
    image: nats:latest
    container_name: atomic-flow-nats
    volumes:
      - ./nats.conf:/etc/nats.conf
    command: "-js -c /etc/nats.conf"
    environment:
      - NATS_USER=${NATS_USER}
      - NATS_TOKEN=${NATS_TOKEN}
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      - atomic-network
    restart: always

networks:
  atomic-network:
    driver: bridge
