// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/task/status": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "summary": "SendStatus receives task status update and publishes to NATS.",
                "parameters": [
                    {
                        "description": "Task status",
                        "name": "status",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/protocol.TaskStatusUpdate"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted"
                    },
                    "400": {
                        "description": "invalid JSON body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "failed to publish to NATS",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "protocol.TaskStatusUpdate": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "mc": {
                    "type": "integer"
                },
                "mode": {
                    "type": "string"
                },
                "progress": {
                    "type": "integer"
                },
                "sem": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "worker": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Fast Atomic Flow API",
	Description:      "Task status receiver and semaphore API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
